Repository quantumlib/ReCirq, pull requests merged in 2021-12, with the labels that each got.

#238 Adds state learning experiment qml_lfe 4/n.
  recirq/qml_lfe/circuit_blocks.py
  recirq/qml_lfe/circuit_blocks_test.py
  recirq/qml_lfe/learn_dynamics_c.py
  recirq/qml_lfe/learn_dynamics_q.py
  recirq/qml_lfe/learn_states_q.py
  recirq/qml_lfe/learn_states_q_test.py
  recirq/qml_lfe/run_config.py
  recirq/qml_lfe/state_flags.py
Labels: cla: yes

#237 CI Testing Matrix
  .github/workflows/pythonpackage.yml
  dev_tools/write-ci-requirements.py
  recirq/fermi_hubbard/extra-requirements.txt
  recirq/hfvqe/extra-requirements.txt
  recirq/qaoa/extra-requirements.txt
  recirq/qaoa/placement.py
  recirq/qaoa/placement_test.py
  requirements.txt
Labels: devops, cla: yes, cirq

#235 Algo Benchmark Library card catalog
  .github/workflows/pythonpackage.yml
  recirq/algorithmic_benchmark_library.py
  recirq/algorithmic_benchmark_library_test.py
  recirq/qaoa/placement.py
Labels: devops, cla: yes, ftb/bl

#244 Add dev_tools/check_notebooks.py
  dev_tools/.gitignore
  dev_tools/check_notebooks.py
  docs/qaoa/optimization_analysis.ipynb
Labels: devops

#222 Intermediate starting states
  recirq/quantum_chess/quantum_board.py
  recirq/quantum_chess/quantum_board_test.py
Labels: chess, cla: yes
