Repository quantumlib/ReCirq, pull requests merged in 2022-04, with the labels that each got.

#279 Implement missing functionality for ASCII quantum board
  recirq/quantum_chess/ascii_board.py
  recirq/quantum_chess/ascii_board_test.py
  recirq/quantum_chess/move.py
  recirq/quantum_chess/move_test.py
Labels: chess

#283 Bump Cirq to 0.14
  .github/workflows/pythonpackage.yml
  dev_tools/write-ci-requirements.py
  requirements.txt
Labels: devops, cirq

#282 Add package data for ftbbl.ipynb
  setup.py
Labels: documentation, ftb/bl
